import { motion } from "motion/react";
import { Navigation } from "./Navigation";

export function Layout({ children }: { children: React.ReactNode }) {
  return (
    <div className="min-h-screen bg-parchment-200 text-guild-ink font-serif overflow-x-hidden relative border-[8px] md:border-[12px] border-parchment-400 box-border p-4 md:p-6 flex flex-col shadow-2xl">
      <div className="fixed inset-0 opacity-5 pointer-events-none" style={{ backgroundImage: 'radial-gradient(var(--color-guild-gold) 1px, transparent 1px)', backgroundSize: '20px 20px' }}></div>
      <header className="flex flex-col md:flex-row justify-between md:items-end mb-6 border-b-2 border-parchment-400 pb-4 px-2 z-10 gap-4">
        <div className="flex flex-col">
          <h1 className="text-4xl font-extrabold tracking-tight text-guild-gold drop-shadow-sm font-sans uppercase">
            NanoShiki's <span className="text-guild-primary font-light">ORARIO</span>
          </h1>
          <p className="text-xs italic text-guild-secondary uppercase tracking-[0.2em] mt-1 font-serif">
            Tower of Babel Network • Established Year 1024
          </p>
        </div>
        <Navigation />
      </header>
      <main className="flex-1 w-full max-w-6xl mx-auto relative z-10">
        <motion.div
          initial={{ opacity: 0, y: 15 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.5, ease: "easeOut" }}
          className="relative h-full"
        >
          {children}
        </motion.div>
      </main>
      <footer className="mt-8 flex flex-col sm:flex-row justify-between items-center text-[10px] uppercase tracking-widest text-guild-secondary border-t border-parchment-300 pt-4 relative z-10 gap-2 text-center">
        <span>Generated by Hestia's Engine v2.4</span>
        <span>© Orario Creative Commune</span>
        <span>Latency: 12ms</span>
      </footer>
    </div>
  );
}
